### ISSUE TITLE
Try statement for inputs.py

### ISSUE THREAD

**Issue by ajkluber** [ajkluber/model_builder#7]
I think it is good practice to avoid try statements when more explicit checks can be done. For example, this [try statement](https://github.com/ajkluber/model_builder/blob/mdtraj_refactor/inputs.py#L279) in inputs. I think a conditional (`if data[3] in key:`) will do the same job (from what I can tell). 

On a related note, I'm not sure what cases the `except` clause is meant for. Is `pot_type = data[3]` intended to anticipate a different input file format?

**Comment by TensorDuck** [comment]
I've added comments to clarify. In short:
1. Check if using the numbered keys, then convert to word keys.
2. If not, check if they are using the word keys instead of the number keys.
3. If it can't find it, it prints an error, with a line number to look at to fix the keys.

**Comment by ajkluber** [comment]
Thanks I think this is resolved.
